### ISSUE TITLE
리액트 팝업 연구해보기

### ISSUE THREAD

**Issue by yceffort** [kjjoo/Todo#9]
리액트로 팝업을 띄울 수 있는 라이브러리 찾아보기
this related with #8

**Comment by joo-ee** [comment]
후보1. https://github.com/yjose/reactjs-popup

**Comment by yceffort** [comment]
이거 설치해서 작업해주세요~~

**Comment by yceffort** [comment]
@kjjoo 위 라이브러리 설치하는 걸로 커밋 푸쉬해서 PR하나 만들어주세요.
